Dont use set -e in unicorn init.d script

diff --git a/roles/unicorn_install/templates/unicorn_init.j2 b/roles/unicorn_install/templates/unicorn_init.j2
--- a/roles/unicorn_install/templates/unicorn_init.j2
+++ b/roles/unicorn_install/templates/unicorn_init.j2
@@ -1,7 +1,4 @@
 #!/bin/sh
-set -e
-# Example init script, this can be used with nginx, too,
-# since nginx and unicorn accept the same signals
 
 TIMEOUT=${TIMEOUT-60}
 RBENV_ROOT="{{ rbenv_root }}"
@@ -11,8 +8,6 @@ PID="$APP_ROOT/tmp/unicorn.pid"
 CMD="$APP_ROOT/bin/unicorn -E {{be_app_env}} -D -c $APP_ROOT/config/unicorn.rb"
 
 action="$1"
-set -u
-
 old_pid="$PID.oldbin"
 
 cd $APP_ROOT || exit 1
@@ -32,7 +27,7 @@ start)
   ;;
 stop)
   sig QUIT && echo "Stopping" && exit 0
-  echo >&2 "Not running"
+  echo >&2 "Unicorn master process with ID `cat $PID` not found (see: $PID)"
   ;;
 force-stop)
   sig TERM && echo "Forcing a stop" && exit 0
